Fix --login-file=<file> crashing the program
Argument <file> was being parsed into a list, rather than into a
string which the code actually expects.

$ sudo -u zabbix python3 ./zbx-hpmsa.py -f /etc/zabbix/credentials/zbx-hpmsa --ssl=direct lld MSA_IP disks
Traceback (most recent call last):
  File "./zbx-hpmsa.py", line 747, in <module>
    CRED_HASH = make_cred_hash(args.login_file, isfile=True)
  File "./zbx-hpmsa.py", line 76, in make_cred_hash
    with open(cred, 'r') as login_file:
TypeError: invalid file: ['/etc/zabbix/credentials/zbx-hpmsa']